// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'TheFooter': typeof import('../components/TheFooter.vue')['default'],
    'TheHeader': typeof import('../components/TheHeader.vue')['default']
  }
}
export {}
